import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,readFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import path from 'node:path';import {spawnSync} from 'node:child_process';
import {CURRENCIES,FACTORS,CALENDAR_FACTORS} from '../lib/config.mjs';import {scoreCurrency,makePairs,pmiPoints,classify,edgeClass,buildReport,observationEligible} from '../lib/scoring.mjs';import {dueSession} from '../lib/schedule.mjs';import {validateResearch,allowedUrl,extractSources} from '../lib/validation.mjs';import {reserveBudget,costUsd,writeJson} from '../lib/storage.mjs';import {markdownReport} from '../lib/markdown.mjs';import {overview,evidence,calendar,history,methodology,details} from '../dist/views.js';
const cutoff='2026-09-17T06:15:00Z',url='https://www.bls.gov/news.release/cpi.htm';
function rows(currency='USD'){return FACTORS.map(f=>({id:`${currency}:${f}`,currency,factor:f,status:'verified',series:f,actual:f==='pmi'?52:1,unit:'%',reading:'1%',consensus:1,prior:1,referencePeriod:'August 2026',sourceName:'Test fixture',sourceUrl:url,sourceDate:'2026-09-10',consensusSourceUrl:url,definitionMatched:true,comparisonMatched:true,tone:'neutral',notes:'Fixture',searchQuery:`${currency} ${f}`}))}
function research(){return {evidence:rows(),events:[],calendarChecks:CALENDAR_FACTORS.map(category=>({currency:'USD',category,status:'none_verified',sourceUrl:url,note:'Fixture calendar'})),risk:{equityChangePct:null,vixChangePct:null,asOf:null,equitySourceUrl:null,vixSourceUrl:null,notes:''}}}
test('PMI boundaries are mutually exclusive',()=>{assert.deepEqual([44.9,45,49.9,50,55,55.1].map(pmiPoints),[-10,-5,-5,3,3,5])});
test('score and edge classification boundaries',()=>{assert.equal(classify(59),'Neutral');assert.equal(classify(60),'Slightly Bullish');assert.deepEqual([10,11,20,21,40,41,60,61].map(edgeClass),['No Edge','Weak Edge','Weak Edge','Tradable Edge','Tradable Edge','Strong Edge','Strong Edge','Exceptional Edge'])});
test('missing consensus does not become a beat against prior',()=>{const r=rows();r.find(x=>x.factor==='employment').consensus=null;r.find(x=>x.factor==='employment').actual=1000;const c=scoreCurrency('USD',r,null,cutoff);assert.equal(c.factors.find(f=>f.id==='employment').points,0);assert.equal(c.factors.find(f=>f.id==='employment').eligible,false)});
test('headline and core conflicting surprises produce one neutral component',()=>{const r=rows();r.find(x=>x.factor==='headline_cpi').actual=1.3;r.find(x=>x.factor==='core_cpi').actual=.7;const c=scoreCurrency('USD',r,null,cutoff);assert.equal(c.factors.filter(f=>f.id==='inflation').length,1);assert.equal(c.factors.find(f=>f.id==='inflation').points,0)});
test('scores recompute from 50 and stay bounded',()=>{const r=rows();for(const e of r)e.actual=5;r.find(e=>e.factor==='employment').actual=1000;r.find(e=>e.factor==='pmi').actual=60;r.find(e=>e.factor==='unemployment').actual=0;r.find(e=>e.factor==='central_bank').tone='strong_hawkish';assert.equal(scoreCurrency('USD',r,{verified:true,regime:'risk_off',reason:'Fixture'},cutoff).score,100);for(const e of r)e.actual=-5;r.find(e=>e.factor==='unemployment').actual=10;r.find(e=>e.factor==='pmi').actual=40;r.find(e=>e.factor==='central_bank').tone='strong_dovish';assert.equal(scoreCurrency('USD',r,null,cutoff).score,0)});
test('future, stale, mismatched and unavailable rows cannot score',()=>{const r=rows();for(const change of [{sourceDate:'2026-10-01'},{sourceDate:'2025-01-01'},{definitionMatched:false},{status:'unavailable'}])assert.equal(observationEligible({...r[0],...change},cutoff),false)});
test('28 conventional pairs, correct direction, neutral threshold and low-evidence guard',()=>{const c=CURRENCIES.map(currency=>({currency,score:50,provisional:false,quality:'High'}));c.find(x=>x.currency==='USD').score=80;c.find(x=>x.currency==='GBP').score=60;const p=makePairs(c);assert.equal(p.length,28);assert.equal(new Set(p.map(p=>p.pair)).size,28);assert.equal(p.find(p=>p.pair==='GBPUSD').direction,'SHORT');c.find(x=>x.currency==='USD').score=70;assert.equal(makePairs(c).find(p=>p.pair==='GBPUSD').direction,'NEUTRAL');c.find(x=>x.currency==='GBP').provisional=true;assert.equal(makePairs(c).find(p=>p.pair==='GBPUSD').direction,'UNRATED')});
test('Vienna schedule handles DST, duplicate runs, windows and weekends',()=>{assert.equal(dueSession(new Date('2026-01-12T07:03:00Z')).session,'morning');assert.equal(dueSession(new Date('2026-07-13T06:03:00Z')).session,'morning');assert.equal(dueSession(new Date('2026-07-13T12:33:00Z')).session,'afternoon');assert.equal(dueSession(new Date('2026-01-12T13:33:00Z')).session,'afternoon');assert.equal(dueSession(new Date('2026-07-13T06:03:00Z'),['2026-07-13-morning']),null);assert.equal(dueSession(new Date('2026-07-13T13:33:00Z')),null);assert.equal(dueSession(new Date('2026-07-18T12:33:00Z')),null);assert.equal(dueSession(new Date('2026-07-18T06:03:00Z')).session,'morning');assert.equal(dueSession(new Date('2026-03-30T06:03:00Z')).session,'morning');assert.equal(dueSession(new Date('2026-10-26T07:03:00Z')).session,'morning')});
test('provenance validation removes uncited evidence and rejects missing searches',()=>{const data=research();const valid=validateResearch(data,['USD'],[],cutoff);assert.ok(valid.evidence.every(e=>e.status==='unavailable'));assert.ok(valid.calendarChecks.every(e=>e.status==='unavailable'));const incomplete=research();incomplete.evidence.pop();assert.throws(()=>validateResearch(incomplete,['USD'],[url],cutoff),/Missing searched category/);assert.equal(allowedUrl('https://bls.gov.evil.test/page'),false);assert.equal(allowedUrl('javascript:alert(1)'),false);assert.equal(allowedUrl(url),true)});
test('invalid consensus, future releases and unsupported event times are not accepted',()=>{const data=research();data.evidence[0].sourceDate='2027-01-01';data.evidence[1].consensusSourceUrl='https://example.org/unverified';data.events=[{currency:'USD',category:'inflation',event:'Fixture',date:'2026-09-18',time:'08:30',timezone:'America/New_York',instant:null,sourceUrl:url,relevance:'Fixture'}];const checked=validateResearch(data,['USD'],[url],cutoff);assert.equal(checked.evidence[0].status,'unavailable');assert.equal(checked.evidence[1].consensus,null);assert.equal(checked.events[0].time,null)});
test('budget reservation blocks additional spend and resets by month',()=>{const n=new Date(cutoff),ledger={month:'2026-09',spent:19,reserved:0,calls:[]};assert.throws(()=>reserveBudget(ledger,1.25,20,n),/BUDGET/);assert.equal(reserveBudget(ledger,1.25,20,new Date('2026-10-01')).spent,0);assert.equal(costUsd({usage:{input_tokens:1000,output_tokens:1000,input_tokens_details:{cached_tokens:0}},output:[{type:'web_search_call'}]}),.01525)});
test('a missing key leaves existing live report and archive intact',async()=>{const dir=await mkdtemp(path.join(tmpdir(),'forex-test-'));try{const data=path.join(dir,'data'),state=path.join(dir,'state');await writeJson(path.join(data,'latest.json'),{id:'last-success',generatedAt:cutoff});const savedArgs=process.argv;const savedEnv={...process.env};const savedExit=process.exitCode;process.argv=[process.execPath,'scripts/run-report.mjs','--session','morning'];Object.assign(process.env,{OPENAI_API_KEY:'',REPORT_DATA_DIR:data,REPORT_STATE_DIR:state,GITHUB_OUTPUT:''});try{await import('../scripts/run-report.mjs');assert.equal(process.exitCode,1)}finally{process.argv=savedArgs;process.env=savedEnv;process.exitCode=savedExit;}assert.equal(JSON.parse(await readFile(path.join(data,'latest.json'))).id,'last-success');assert.equal(JSON.parse(await readFile(path.join(data,'status.json'))).status,'not_configured')}finally{await rm(dir,{recursive:true,force:true})}});
test('reports have tied ranks, exactly five bullets, all sections and renderable views',()=>{const r=buildReport(CURRENCIES.flatMap(rows),null,[],[],{id:'fixture',cutoff,session:'morning'});assert.equal(r.summary.length,5);assert.ok(r.currencies.every(c=>c.rank===1));assert.equal((markdownReport(r).match(/## Section /g)||[]).length,7);const ctx={report:r,index:[],method:{sources:{},labels:{},thresholds:{}},currencyFilter:'all'};for(const render of [overview,evidence,calendar,history,methodology])assert.ok(render(ctx).length>100);assert.ok(details(r,'USD').includes('Neutral starting point'))});
test('web citations and sources are collected for provenance',()=>{assert.deepEqual(extractSources({output:[{action:{sources:[{url}]}},{content:[{annotations:[{url}]}]}]}),[url])});
