import {CURRENCIES,FACTORS,LABELS,THRESHOLDS,maxAge,MODEL_VERSION} from './config.mjs';
export function classify(s){return s>=90?'Extremely Bullish':s>=80?'Strong Bullish':s>=70?'Bullish':s>=60?'Slightly Bullish':s>=40?'Neutral':s>=30?'Slightly Bearish':s>=20?'Bearish':s>=10?'Strong Bearish':'Extremely Bearish';}
export function edgeClass(e){return e<=10?'No Edge':e<=20?'Weak Edge':e<=40?'Tradable Edge':e<=60?'Strong Edge':'Exceptional Edge';}
export function pmiPoints(v){return v<45?-10:v<50?-5:v<=55?3:5;}
const finite=v=>typeof v==='number'&&Number.isFinite(v);
export function observationEligible(row,cutoff){if(!row||row.status!=='verified'||!row.sourceUrl||!row.sourceDate||!row.definitionMatched)return false;const days=(Date.parse(cutoff)-Date.parse(row.sourceDate))/86400000;return Number.isFinite(days)&&days>=0&&days<=maxAge(row.currency,row.factor);}
function delta(row,cutoff){return observationEligible(row,cutoff)&&finite(row.actual)&&finite(row.consensus)&&row.consensusSourceUrl&&row.comparisonMatched?Math.round((row.actual-row.consensus)*1e8)/1e8:null;}
function surprise(d,[small,large],negativeLarge=-10){if(d===null||Math.abs(d)<small)return 0;return d>0?(d>=large?10:5):(Math.abs(d)>=large?negativeLarge:-5);}
export function scoreCurrency(currency,rows,risk,cutoff){
 const by=Object.fromEntries(rows.filter(r=>r.currency===currency).map(r=>[r.factor,r]));const t=THRESHOLDS[currency];const factors=[];
 const add=(id,points,reason,evidence,eligible=true)=>factors.push({id,label:LABELS[id],points,reason,evidenceIds:evidence.filter(Boolean).map(r=>r.id),eligible});
 const cb=by.central_bank;const cbOk=observationEligible(cb,cutoff)&&observationEligible(by.rate_decision,cutoff);const tones={strong_hawkish:15,moderate_hawkish:10,neutral:0,mixed:0,moderate_dovish:-10,strong_dovish:-15};
 add('central_bank',cbOk?(tones[cb.tone]??0):0,cbOk?`${cb.notes} Rate decision is context within this single policy adjustment.`:'Policy guidance or rate decision is missing, stale, or not verified; no policy adjustment.',[cb,by.rate_decision],cbOk);
 const h=delta(by.headline_cpi,cutoff),c=delta(by.core_cpi,cutoff);const hs=surprise(h,t.cpi),cs=surprise(c,t.cpi);let ip=0,ir='Inflation consensus is unavailable or incomparable; no surprise adjustment.';
 if(h!==null&&c!==null){ip=hs*cs<0?0:Math.round((hs*.4+cs*.6)/5)*5;ir=hs*cs<0?'Headline and core surprises point in opposite directions; mixed evidence, 0 points.':`Headline surprise ${h} pp (40%); core surprise ${c} pp (60%). Weighted component rounded to the nearest 5 points.`;}else if(h!==null||c!==null){ip=h!==null?hs:cs;ir=`Only ${h!==null?'headline':'core'} has comparable consensus: surprise ${h??c} pp. Use the available component once; evidence coverage reduced.`;}
 add('inflation',ip,ir,[by.headline_cpi,by.core_cpi],h!==null&&c!==null);
 const e=delta(by.employment,cutoff);const ep=e===null||Math.abs(e)<t.employment[0]?0:e<0?-10:e>=t.employment[1]?10:5;
 add('employment',ep,e===null?'No comparable employment consensus; no adjustment.':`Employment surprise ${e} ${by.employment.unit}; thresholds ${t.employment.join(' / ')}. ${by.employment.notes}`,[by.employment],e!==null);
 const u=by.unemployment;const uOk=observationEligible(u,cutoff)&&finite(u.actual)&&finite(u.prior);const ud=uOk?Math.round((u.actual-u.prior)*1e8)/1e8:0;
 add('unemployment',uOk&&Math.abs(ud)>=.05?(ud<0?5:-5):0,uOk?`Unemployment ${u.actual}% versus prior ${u.prior}%. Scored only here; employment counts are separate.`:'Comparable unemployment actual/prior unavailable.',[u],uOk);
 const g=delta(by.gdp,cutoff);add('gdp',surprise(g,t.gdp),g===null?'Comparable GDP consensus unavailable.':`GDP surprise ${g} pp on the configured growth basis. Thresholds ${t.gdp.join(' / ')} pp.`,[by.gdp],g!==null);
 const p=by.pmi;const pOk=observationEligible(p,cutoff)&&finite(p.actual)&&p.actual>=0&&p.actual<=100;add('pmi',pOk?pmiPoints(p.actual):0,pOk?`${p.series}: ${p.actual}. Bands: <45, 45–<50, 50–55, >55. One series only.`:'The configured PMI series is unavailable or stale.',[p],pOk);
 const r=delta(by.retail_sales,cutoff);add('retail_sales',r!==null&&Math.abs(r)>=t.retail?(r>0?5:-5):0,r===null?'Comparable spending consensus unavailable.':`Spending surprise ${r} pp; ${by.retail_sales.series}.`,[by.retail_sales],r!==null);
 // Risk must be constructed from observed equity and VIX changes, not LLM judgement.
 const riskOk=risk?.verified===true;const rp=riskOk&&((risk.regime==='risk_on'&&['AUD','NZD'].includes(currency))||(risk.regime==='risk_off'&&['USD','JPY','CHF'].includes(currency)))?5:0;
 add('risk',rp,riskOk?risk.reason:'Fresh equity / volatility evidence unavailable; risk adjustment withheld.',[],riskOk);
 const verified=FACTORS.filter(f=>observationEligible(by[f],cutoff)).length,eligible=factors.filter(f=>f.eligible).length;const score=Math.max(0,Math.min(100,50+factors.reduce((n,f)=>n+f.points,0)));
 const quality=verified>=8&&eligible>=7?'High':verified>=6&&eligible>=4?'Medium':'Low';const nz=factors.filter(f=>f.points!==0),agreement=nz.length<2?'Mixed':Math.max(nz.filter(f=>f.points>0).length,nz.filter(f=>f.points<0).length)/nz.length>=.8?'Strong':'Mixed';
 return {currency,score,bias:classify(score),quality,agreement,verifiedFactors:verified,totalFactors:9,eligibleComponents:eligible,provisional:quality==='Low',factors};
}
// Conventional base/quote ordering. No inverse duplicates.
const ORDER=['EUR','GBP','AUD','NZD','USD','CAD','CHF','JPY'];
export function makePairs(currencies){const map=Object.fromEntries(currencies.map(c=>[c.currency,c]));return ORDER.flatMap((a,i)=>ORDER.slice(i+1).map(b=>{const d=map[a].score-map[b].score;const eligible=!map[a].provisional&&!map[b].provisional;return {pair:a+b,base:a,quote:b,difference:d,edge:Math.abs(d),edgeClass:edgeClass(Math.abs(d)),direction:!eligible?'UNRATED':Math.abs(d)<=10?'NEUTRAL':d>0?'LONG':'SHORT',eligible,quality:[map[a].quality,map[b].quality].includes('Low')?'Low':[map[a].quality,map[b].quality].includes('Medium')?'Medium':'High'};})).sort((a,b)=>b.edge-a.edge||a.pair.localeCompare(b.pair));}
export function buildReport(evidence,risk,events,calendarChecks,{cutoff,session,id,generatedAt=new Date().toISOString()}){
 const currencies=CURRENCIES.map(c=>scoreCurrency(c,evidence,risk,cutoff)).sort((a,b)=>b.score-a.score||CURRENCIES.indexOf(a.currency)-CURRENCIES.indexOf(b.currency));let rank=0;currencies.forEach((c,i)=>{if(i===0||c.score!==currencies[i-1].score)rank=i+1;c.rank=rank;});
 const pairs=makePairs(currencies),focus=pairs.find(p=>p.pair==='GBPUSD');const qualified=pairs.filter(p=>p.eligible&&p.edge>10);const leader=currencies.filter(c=>c.score===currencies[0].score).map(c=>c.currency).join(' / '),laggard=currencies.filter(c=>c.score===currencies.at(-1).score).map(c=>c.currency).join(' / ');
 const next=[...events].sort((a,b)=>a.date.localeCompare(b.date)||String(a.time).localeCompare(String(b.time)))[0];
 const summary=[`${leader} leads at ${currencies[0].score}/100 under the fundamental model${currencies[0].provisional?'; evidence is incomplete':''}.`,`${laggard} ranks lowest at ${currencies.at(-1).score}/100${currencies.at(-1).provisional?'; treat this as provisional':''}.`,qualified.length?`Largest eligible separation: ${qualified[0].pair}, ${qualified[0].edge} points (${qualified[0].edgeClass}); favor ${qualified[0].direction==='LONG'?qualified[0].base:qualified[0].quote}.`:'No adequately supported directional pair edge is available.',focus.direction==='UNRATED'?'GBPUSD is unrated: evidence quality is insufficient.':focus.direction==='NEUTRAL'?'GBPUSD is neutral; wait for clearer fundamental separation.':`GBPUSD: only look for ${focus.direction} setups; ${focus.edge}-point separation.`,next?`Next verified event: ${next.currency} ${next.event}, ${next.date}${next.time?' at '+next.time+' '+next.timezone:''}. ${next.relevance}`:'No upcoming event was verified; consult the calendar coverage notes before trading.'];
 return {id,modelVersion:MODEL_VERSION,demo:false,status:currencies.some(c=>c.provisional)?'partial':'verified',cutoff,generatedAt,session,timezone:'Europe/Vienna',currencies,pairs,focus,summary,evidence,risk,events,calendarChecks,limitations:currencies.filter(c=>c.provisional).map(c=>`${c.currency}: ${c.verifiedFactors}/9 current factors verified; directional handoff withheld.`)};
}
